### ISSUE TITLE
Liveview Sony Alpha6300

### ISSUE THREAD

**Issue by nicknick25** [PhotoboothProject/photobooth#628] opened 2024-03-01 15:00 UTC
### Describe the bug

Hello, I have a problem with my Sony Alpha 6300. I would like to use the live view function.

### Steps to reproduce the behavior

I proceeded as it says in the FAQ.

Preview mode
from device cam(no remote)

Capture image from preview from device camera. Turned on

Command to trigger the camera

python3 cameracontrol.py --capture-image-and-download %s

Command to create a live preview
python3 cameracontrol.py

Now when I take a picture, the Cheees appears and then an error message appears and the page is reloaded. Now I have neither a picture nor a live view.

### Expected behavior

Liveview

### Photobooth Version

4.4.1

### Did it work before?

Yes

### Latest working version

4.4.1

**Comment by andi34** [comment] 2024-03-01 15:23
Duplicate of https://github.com/PhotoboothProject/photobooth/issues/527

**Closed as completed by andi34** 2024-03-01 15:23 UTC
