### ISSUE TITLE
[BUG]: Live View Eos 1300D

### ISSUE THREAD

**Issue by Tobi392** [PhotoboothProject/photobooth#572] opened 2024-01-26 20:50 UTC
### Describe the bug

Hi,
Live view with the Canon EOS 1300D is not working.
Take picture command python3 cameracontrol.py --capture-image-and-download %s works fine.
If I'm using the command python3 cameracontrol.py --bsm for live view preview the shutter clicks the whole time but no preview will be displayed. Also no picture will be taken. Seems to be like a loop. The cheese screen is displayed the whole time.

### Steps to reproduce the behavior

[2024-01-26 20:28:05][main][ERROR] error {"error":"File was not created","cmd":"python3 cameracontrol.py --capture-image-and-download /var/www/html/data/tmp/20240126_202801.jpg 2>&1","returnValue":1,"output":["Traceback (most recent call last):","  File \"/var/www/html/api/cameracontrol.py\", line 726, in ","    sys.exit(main())","             ^^^^^^","  File \"/var/www/html/api/cameracontrol.py\", line 691, in main","    cam = CameraControl(args)","          ^^^^^^^^^^^^^^^^^^^","  File \"/var/www/html/api/cameracontrol.py\", line 100, in __init__","    self.connect_to_camera()","  File \"/var/www/html/api/cameracontrol.py\", line 120, in connect_to_camera","    raise CouldNotConnectException()","CouldNotConnectException"]}
[2024-01-26 20:48:26][main][ERROR] error {"error":"File was not created","cmd":"python3 cameracontrol.py --capture-image-and-download /var/www/html/data/tmp/20240126_204822.jpg 2>&1","returnValue":1,"output":["Traceback (most recent call last):","  File \"/var/www/html/api/cameracontrol.py\", line 726, in ","    sys.exit(main())","             ^^^^^^","  File \"/var/www/html/api/cameracontrol.py\", line 691, in main","    cam = CameraControl(args)","          ^^^^^^^^^^^^^^^^^^^","  File \"/var/www/html/api/cameracontrol.py\", line 100, in __init__","    self.connect_to_camera()","  File \"/var/www/html/api/cameracontrol.py\", line 120, in connect_to_camera","    raise CouldNotConnectException()","CouldNotConnectException"]}

################################
Config: ui
----------------
Subconfig: language
Value:     "en"
----------------
Subconfig: folders_lang
Value:     "resources\/lang"
----------------
Subconfig: notification_timeout
Value:     "5"
----------------
Subconfig: show_fork
Value:     false
----------------
Subconfig: skip_welcome
Value:     false
----------------
Subconfig: admin_shortcut
Value:     true
----------------
Subconfig: admin_shortcut_position
Value:     "bottom-right"
----------------
Subconfig: style
Value:     "modern_squared"
----------------
Subconfig: button
Value:     "modern_squared"
----------------
Subconfig: shutter_animation
Value:     false
----------------
Subconfig: shutter_cheese_img
Value:     ""
----------------
Subconfig: result_buttons
Value:     true
----------------
Subconfig: font_size
Value:     "16px"
----------------
Subconfig: decore_lines
Value:     true
----------------
Subconfig: rounded_corners
Value:     false
----------------
Subconfig: branding
Value:     "Photobooth"
----------------
################################
Config: adminpanel
----------------
Subconfig: view
Value:     "expert"
----------------
Subconfig: experimental_settings
Value:     false
----------------
Subconfig: view_default
Value:     "expert"
----------------
################################
Config: dev
----------------
Subconfig: loglevel
Value:     "1"
----------------
Subconfig: demo_images
Value:     false
----------------
Subconfig: reload_on_error
Value:     true
----------------
################################
Config: start_screen
----------------
Subconfig: title
Value:     ""
----------------
Subconfig: title_visible
Value:     false
----------------
Subconfig: subtitle
Value:     ""
----------------
Subconfig: subtitle_visible
Value:     false
----------------
################################
Config: picture
----------------
Subconfig: thumb_size
Value:     "540px"
----------------
Subconfig: time_to_live
Value:     "90"
----------------
Subconfig: preview_before_processing
Value:     false
----------------
Subconfig: retry_on_error
Value:     "0"
----------------
Subconfig: retry_timeout
Value:     "2"
----------------
Subconfig: enabled
Value:     true
----------------
Subconfig: cntdwn_time
Value:     "8"
----------------
Subconfig: cheese_time
Value:     "1000"
----------------
Subconfig: flip
Value:     "off"
----------------
Subconfig: rotation
Value:     "0"
----------------
Subconfig: polaroid_effect
Value:     false
----------------
Subconfig: polaroid_rotation
Value:     "0"
----------------
Subconfig: take_frame
Value:     true
----------------
Subconfig: frame
Value:     "\/api\/randomImg.php?dir=demoframes"
----------------
Subconfig: extend_by_frame
Value:     true
----------------
Subconfig: frame_left_percentage
Value:     10
----------------
Subconfig: frame_right_percentage
Value:     10
----------------
Subconfig: frame_top_percentage
Value:     5
----------------
Subconfig: frame_bottom_percentage
Value:     15
----------------
Subconfig: key
Value:     ""
----------------
Subconfig: naming
Value:     "dateformatted"
----------------
Subconfig: permissions
Value:     "0644"
----------------
Subconfig: keep_original
Value:     true
----------------
Subconfig: preserve_exif_data
Value:     false
----------------
Subconfig: allow_delete
Value:     true
----------------
################################
Config: reload
----------------
Subconfig: key
Value:     ""
----------------
################################
Config: webserver
----------------
Subconfig: ip
Value:     "192.168.178.44"
----------------
Subconfig: ssid
Value:     "Photobooth"
----------------
################################
Config: download
----------------
Subconfig: enabled
Value:     true
----------------
Subconfig: thumbs
Value:     false
----------------
################################
Config: delete
----------------
Subconfig: no_request
Value:     false
----------------
################################
Config: database
----------------
Subconfig: enabled
Value:     true
----------------
Subconfig: file
Value:     "db"
----------------
################################
Config: logo
----------------
Subconfig: enabled
Value:     false
----------------
Subconfig: path
Value:     "\/resources\/img\/logo\/logo-qrcode-text.png"
----------------
Subconfig: position
Value:     "center"
----------------
################################
Config: event
----------------
Subconfig: enabled
Value:     false
----------------
Subconfig: textLeft
Value:     ""
----------------
Subconfig: symbol
Value:     "fa-heart-o"
----------------
Subconfig: textRight
Value:     ""
----------------
################################
Config: button
----------------
Subconfig: force_buzzer
Value:     false
----------------
Subconfig: show_cups
Value:     false
----------------
Subconfig: show_fs
Value:     false
----------------
Subconfig: homescreen
Value:     true
----------------
Subconfig: reload
Value:     false
----------------
################################
Config: filters
----------------
Subconfig: enabled
Value:     true
----------------
Subconfig: defaults
Value:     "plain"
----------------
Subconfig: disabled
Value:     
----------------
################################
Config: textonpicture
----------------
Subconfig: enabled
Value:     false
----------------
Subconfig: line1
Value:     "line 1"
----------------
Subconfig: line2
Value:     "line 2"
----------------
Subconfig: line3
Value:     "line 3"
----------------
Subconfig: locationx
Value:     "80"
----------------
Subconfig: locationy
Value:     "80"
----------------
Subconfig: rotation
Value:     "0"
----------------
Subconfig: font
Value:     "\/resources\/fonts\/GreatVibes-Regular.ttf"
----------------
Subconfig: font_color
Value:     "#ffffff"
----------------
Subconfig: font_size
Value:     "80"
----------------
Subconfig: linespace
Value:     "90"
----------------
################################
Config: custom
----------------
Subconfig: enabled
Value:     false
----------------
Subconfig: cntdwn_time
Value:     "5"
----------------
Subconfig: key
Value:     ""
----------------
Subconfig: btn_text
Value:     "Custom"
----------------
################################
Config: take_custom
----------------
Subconfig: cmd
Value:     ""
----------------
################################
Config: get_request
----------------
Subconfig: custom
Value:     "CNTDWNCUSTOM"
----------------
Subconfig: countdown
Value:     false
----------------
Subconfig: processed
Value:     false
----------------
Subconfig: server
Value:     ""
----------------
Subconfig: picture
Value:     "CNTDWNPHOTO"
----------------
Subconfig: collage
Value:     "CNTDWNCOLLAGE"
----------------
Subconfig: video
Value:     "CNTDWNVIDEO"
----------------
################################
Config: icons
----------------
Subconfig: take_custom
Value:     "fa fa-paint-brush"
----------------
Subconfig: admin_back
Value:     "fa fa-long-arrow-left"
----------------
Subconfig: admin_back_short
Value:     "fa fa-arrow-left"
----------------
Subconfig: admin_menutoggle
Value:     "fa fa-bars"
----------------
Subconfig: admin_save
Value:     "fa fa-circle-notch fa-spin fa-fw"
----------------
Subconfig: admin_save_success
Value:     "fa fa-check"
----------------
Subconfig: admin_save_error
Value:     "fa fa-times"
----------------
Subconfig: admin_signout
Value:     "fa fa-sign-out"
----------------
Subconfig: admin
Value:     "fa fa-cog"
----------------
Subconfig: home
Value:     "fa fa-house"
----------------
Subconfig: gallery
Value:     "fa fa-image"
----------------
Subconfig: dependencies
Value:     "fa fa-list-ul"
----------------
Subconfig: update
Value:     "fa fa-tasks"
----------------
Subconfig: slideshow
Value:     "fa fa-play"
----------------
Subconfig: chromaCapture
Value:     "fa fa-paint-brush"
----------------
Subconfig: faq
Value:     "fa fa-question-circle"
----------------
Subconfig: manual
Value:     "fa fa-info-circle"
----------------
Subconfig: telegram
Value:     "fa-brands fa-telegram"
----------------
Subconfig: cups
Value:     "fa fa-print"
----------------
Subconfig: take_picture
Value:     "fa fa-camera"
----------------
Subconfig: take_collage
Value:     "fa fa-th-large"
----------------
Subconfig: take_video
Value:     "fa fa-video"
----------------
Subconfig: close
Value:     "fa fa-times"
----------------
Subconfig: refresh
Value:     "fa fa-arrows-rotate"
----------------
Subconfig: delete
Value:     "fa fa-trash-can"
----------------
Subconfig: print
Value:     "fa fa-print"
----------------
Subconfig: save
Value:     "fa fa-floppy-disk"
----------------
Subconfig: download
Value:     "fa fa-download"
----------------
Subconfig: qr
Value:     "fa fa-qrcode"
----------------
Subconfig: mail
Value:     "fa fa-envelope"
----------------
Subconfig: mail_close
Value:     "fa fa-times"
----------------
Subconfig: mail_submit
Value:     "fa fa-spinner fa-spin"
----------------
Subconfig: filter
Value:     "fa fa-wand-magic-sparkles"
----------------
Subconfig: chroma
Value:     "fa fa-paint-brush"
----------------
Subconfig: fullscreen
Value:     "fa fa-maximize"
----------------
Subconfig: share
Value:     "fa fa-share-alt"
----------------
Subconfig: zoom
Value:     "fa fa-search-plus"
----------------
Subconfig: logout
Value:     "fa fa-right-from-bracket"
----------------
Subconfig: date
Value:     "fa fa-clock"
----------------
Subconfig: spinner
Value:     "fa fa-cog fa-spin"
----------------
Subconfig: update_git
Value:     "fa fa-play-circle"
----------------
Subconfig: password_visibility
Value:     "fa fa-eye"
----------------
Subconfig: password_toggle
Value:     "fa-eye fa-eye-slash"
----------------
Subconfig: slideshow_play
Value:     "fa fa-play"
----------------
Subconfig: slideshow_toggle
Value:     "fa-play fa-pause"
----------------
################################
Config: collage
----------------
Subconfig: enabled
Value:     true
----------------
Subconfig: cntdwn_time
Value:     "3"
----------------
Subconfig: continuous
Value:     true
----------------
Subconfig: continuous_time
Value:     "5"
----------------
Subconfig: layout
Value:     "2+2-2"
----------------
Subconfig: resolution
Value:     "300dpi"
----------------
Subconfig: dashedline_color
Value:     "#000000"
----------------
Subconfig: keep_single_images
Value:     false
----------------
Subconfig: key
Value:     ""
----------------
Subconfig: background_color
Value:     "#ffffff"
----------------
Subconfig: take_frame
Value:     "off"
----------------
Subconfig: frame
Value:     "\/resources\/img\/frames\/frame.png"
----------------
Subconfig: placeholder
Value:     false
----------------
Subconfig: placeholderposition
Value:     "1"
----------------
Subconfig: placeholderpath
Value:     "\/resources\/img\/background\/01.jpg"
----------------
Subconfig: background
Value:     ""
----------------
Subconfig: limit
Value:     4
----------------
################################
Config: textoncollage
----------------
Subconfig: enabled
Value:     true
----------------
Subconfig: line1
Value:     "Photobooth"
----------------
Subconfig: line2
Value:     "   we love"
----------------
Subconfig: line3
Value:     "OpenSource"
----------------
Subconfig: locationx
Value:     "1470"
----------------
Subconfig: locationy
Value:     "250"
----------------
Subconfig: rotation
Value:     "0"
----------------
Subconfig: font
Value:     "\/resources\/fonts\/GreatVibes-Regular.ttf"
----------------
Subconfig: font_color
Value:     "#000000"
----------------
Subconfig: font_size
Value:     "50"
----------------
Subconfig: linespace
Value:     "90"
----------------
################################
Config: video
----------------
Subconfig: enabled
Value:     false
----------------
Subconfig: cntdwn_time
Value:     "3"
----------------
Subconfig: cheese
Value:     "Show your moves!"
----------------
Subconfig: collage
Value:     false
----------------
Subconfig: collage_keep_images
Value:     false
----------------
Subconfig: collage_only
Value:     false
----------------
Subconfig: effects
Value:     "none"
----------------
Subconfig: animation
Value:     true
----------------
Subconfig: gif
Value:     false
----------------
Subconfig: qr
Value:     true
----------------
################################
Config: gallery
----------------
Subconfig: enabled
Value:     true
----------------
Subconfig: newest_first
Value:     true
----------------
Subconfig: use_slideshow
Value:     true
----------------
Subconfig: pictureTime
Value:     "3000"
----------------
Subconfig: show_date
Value:     true
----------------
Subconfig: date_format
Value:     "d.m.Y - G:i"
----------------
Subconfig: db_check_enabled
Value:     true
----------------
Subconfig: db_check_time
Value:     "10"
----------------
Subconfig: allow_delete
Value:     true
----------------
Subconfig: scrollbar
Value:     false
----------------
Subconfig: bottom_bar
Value:     true
----------------
Subconfig: figcaption
Value:     true
----------------
Subconfig: action_footer
Value:     false
----------------
################################
Config: pswp
----------------
Subconfig: counterEl
Value:     true
----------------
Subconfig: caption
Value:     true
----------------
Subconfig: clickToCloseNonZoomable
Value:     false
----------------
Subconfig: pinchToClose
Value:     true
----------------
Subconfig: closeOnVerticalDrag
Value:     true
----------------
Subconfig: zoomEl
Value:     false
----------------
Subconfig: loop
Value:     true
----------------
Subconfig: bgOpacity
Value:     1
----------------
Subconfig: imageClickAction
Value:     "toggle-controls"
----------------
Subconfig: tapAction
Value:     "toggle-controls"
----------------
Subconfig: doubleTapAction
Value:     "zoom"
----------------
Subconfig: bgClickAction
Value:     "none"
----------------
################################
Config: preview
----------------
Subconfig: mode
Value:     "device_cam"
----------------
Subconfig: stop_time
Value:     "2"
----------------
Subconfig: camTakesPic
Value:     false
----------------
Subconfig: style
Value:     "scale-down"
----------------
Subconfig: flip
Value:     "off"
----------------
Subconfig: rotation
Value:     "0deg"
----------------
Subconfig: url
Value:     ""
----------------
Subconfig: url_delay
Value:     "1000"
----------------
Subconfig: videoWidth
Value:     "1280"
----------------
Subconfig: videoHeight
Value:     "720"
----------------
Subconfig: camera_mode
Value:     "user"
----------------
Subconfig: asBackground
Value:     false
----------------
Subconfig: showFrame
Value:     false
----------------
Subconfig: cmd
Value:     "python3 cameracontrol.py --bsm"
----------------
Subconfig: killcmd
Value:     ""
----------------
Subconfig: simpleExec
Value:     true
----------------
Subconfig: bsm
Value:     true
----------------
################################
Config: keying
----------------
Subconfig: enabled
Value:     false
----------------
Subconfig: size
Value:     "1500px"
----------------
Subconfig: variant
Value:     "seriouslyjs"
----------------
Subconfig: seriouslyjs_color
Value:     "#62af74"
----------------
Subconfig: background_path
Value:     "resources\/img\/background"
----------------
Subconfig: show_all
Value:     false
----------------
################################
Config: chromaCapture
----------------
Subconfig: enabled
Value:     false
----------------
################################
Config: print
----------------
Subconfig: from_result
Value:     false
----------------
Subconfig: from_gallery
Value:     false
----------------
Subconfig: from_chromakeying
Value:     false
----------------
Subconfig: auto
Value:     false
----------------
Subconfig: auto_delay
Value:     "1000"
----------------
Subconfig: time
Value:     "5000"
----------------
Subconfig: limit
Value:     "0"
----------------
Subconfig: locking_msg
Value:     "Printing... Print limit reached, print will be locked."
----------------
Subconfig: limit_msg
Value:     "Print locked."
----------------
Subconfig: no_rotate
Value:     false
----------------
Subconfig: key
Value:     ""
----------------
Subconfig: qrcode
Value:     false
----------------
Subconfig: qrSize
Value:     "4"
----------------
Subconfig: qrPosition
Value:     "bottomRight"
----------------
Subconfig: qrOffset
Value:     10
----------------
Subconfig: qrMargin
Value:     "4"
----------------
Subconfig: qrBgColor
Value:     "#ffffff"
----------------
Subconfig: print_frame
Value:     false
----------------
Subconfig: frame
Value:     "\/resources\/img\/frames\/frame.png"
----------------
Subconfig: crop
Value:     false
----------------
Subconfig: crop_width
Value:     "1000"
----------------
Subconfig: crop_height
Value:     "500"
----------------
Subconfig: cmd
Value:     "lp -o landscape -o fit-to-page %s"
----------------
################################
Config: textonprint
----------------
Subconfig: enabled
Value:     false
----------------
Subconfig: line1
Value:     "line 1"
----------------
Subconfig: line2
Value:     "line 2"
----------------
Subconfig: line3
Value:     "line 3"
----------------
Subconfig: locationx
Value:     "2250"
----------------
Subconfig: locationy
Value:     "1050"
----------------
Subconfig: rotation
Value:     "40"
----------------
Subconfig: font
Value:     "\/resources\/fonts\/GreatVibes-Regular.ttf"
----------------
Subconfig: font_color
Value:     "#ffffff"
----------------
Subconfig: font_size
Value:     "100"
----------------
Subconfig: linespace
Value:     "100"
----------------
################################
Config: qr
----------------
Subconfig: enabled
Value:     true
----------------
Subconfig: url
Value:     "\/api\/download.php?image="
----------------
Subconfig: append_filename
Value:     true
----------------
Subconfig: custom_text
Value:     false
----------------
Subconfig: text
Value:     ""
----------------
Subconfig: result
Value:     "hidden"
----------------
################################
Config: mail
----------------
Subconfig: enabled
Value:     false
----------------
Subconfig: send_all_later
Value:     false
----------------
Subconfig: subject
Value:     "Hier ist dein Bild"
----------------
Subconfig: text
Value:     "Hey, dein Bild ist angehangen."
----------------
Subconfig: alt_text
Value:     ""
----------------
Subconfig: is_html
Value:     false
----------------
Subconfig: host
Value:     "smtp.example.com"
----------------
Subconfig: username
Value:     "photobooth@example.com"
----------------
Subconfig: password
Value:     "yourpassword"
----------------
Subconfig: fromAddress
Value:     "photobooth@example.com"
----------------
Subconfig: fromName
Value:     "Photobooth"
----------------
Subconfig: file
Value:     "mail-adresses"
----------------
Subconfig: secure
Value:     "tls"
----------------
Subconfig: port
Value:     "587"
----------------
################################
Config: slideshow
----------------
Subconfig: refreshTime
Value:     "60"
----------------
Subconfig: pictureTime
Value:     "3000"
----------------
Subconfig: randomPicture
Value:     true
----------------
Subconfig: use_thumbs
Value:     false
----------------
################################
Config: remotebuzzer
----------------
Subconfig: startserver
Value:     false
----------------
Subconfig: serverip
Value:     "192.168.178.44"
----------------
Subconfig: port
Value:     14711
----------------
Subconfig: usebuttons
Value:     false
----------------
Subconfig: userotary
Value:     false
----------------
Subconfig: enable_standalonegallery
Value:     false
----------------
Subconfig: usenogpio
Value:     false
----------------
Subconfig: picturebutton
Value:     true
----------------
Subconfig: collagetime
Value:     "2"
----------------
Subconfig: collagebutton
Value:     false
----------------
Subconfig: printbutton
Value:     false
----------------
Subconfig: shutdownbutton
Value:     false
----------------
Subconfig: shutdownholdtime
Value:     "5"
----------------
Subconfig: debounce
Value:     30
----------------
Subconfig: rebootbutton
Value:     false
----------------
Subconfig: rebootholdtime
Value:     "5"
----------------
Subconfig: useleds
Value:     false
----------------
Subconfig: photolight
Value:     false
----------------
Subconfig: pictureled
Value:     false
----------------
Subconfig: collageled
Value:     false
----------------
Subconfig: shutdownled
Value:     false
----------------
Subconfig: rebootled
Value:     false
----------------
Subconfig: printled
Value:     false
----------------
Subconfig: videobutton
Value:     false
----------------
Subconfig: videoled
Value:     false
----------------
Subconfig: custombutton
Value:     false
----------------
Subconfig: customled
Value:     false
----------------
Subconfig: move2usb
Value:     "disabled"
----------------
Subconfig: move2usbled
Value:     false
----------------
Subconfig: rotaryclkgpio
Value:     27
----------------
Subconfig: rotarydtgpio
Value:     17
----------------
Subconfig: rotarybtngpio
Value:     22
----------------
Subconfig: picturegpio
Value:     21
----------------
Subconfig: collagegpio
Value:     20
----------------
Subconfig: printgpio
Value:     26
----------------
Subconfig: shutdowngpio
Value:     16
----------------
Subconfig: rebootgpio
Value:     8
----------------
Subconfig: photolightgpio
Value:     25
----------------
Subconfig: pictureledgpio
Value:     19
----------------
Subconfig: collageledgpio
Value:     12
----------------
Subconfig: shutdownledgpio
Value:     23
----------------
Subconfig: rebootledgpio
Value:     18
----------------
Subconfig: printledgpio
Value:     10
----------------
Subconfig: videogpio
Value:     7
----------------
Subconfig: videoledgpio
Value:     9
----------------
Subconfig: customgpio
Value:     5
----------------
Subconfig: customledgpio
Value:     24
----------------
Subconfig: move2usbgpio
Value:     6
----------------
Subconfig: move2usbledgpio
Value:     11
----------------
################################
Config: synctodrive
----------------
Subconfig: enabled
Value:     false
----------------
Subconfig: target
Value:     "photobooth"
----------------
Subconfig: interval
Value:     300
----------------
################################
Config: ftp
----------------
Subconfig: enabled
Value:     false
----------------
Subconfig: baseURL
Value:     ""
----------------
Subconfig: port
Value:     21
----------------
Subconfig: username
Value:     ""
----------------
Subconfig: password
Value:     ""
----------------
Subconfig: baseFolder
Value:     ""
----------------
Subconfig: folder
Value:     ""
----------------
Subconfig: title
Value:     ""
----------------
Subconfig: appendDate
Value:     false
----------------
Subconfig: useForQr
Value:     false
----------------
Subconfig: website
Value:     ""
----------------
Subconfig: urlTemplate
Value:     ""
----------------
Subconfig: create_webpage
Value:     false
----------------
Subconfig: template_location
Value:     "\/var\/www\/html\/resources\/template\/index.php"
----------------
Subconfig: upload_thumb
Value:     false
----------------
Subconfig: delete
Value:     false
----------------
################################
Config: login
----------------
Subconfig: enabled
Value:     false
----------------
Subconfig: username
Value:     "Photo"
----------------
Subconfig: password
Value:     ""
----------------
Subconfig: keypad
Value:     false
----------------
Subconfig: pin
Value:     ""
----------------
Subconfig: rental_keypad
Value:     false
----------------
Subconfig: rental_pin
Value:     ""
----------------
################################
Config: protect
----------------
Subconfig: admin
Value:     true
----------------
Subconfig: localhost_admin
Value:     true
----------------
Subconfig: index
Value:     false
----------------
Subconfig: localhost_index
Value:     false
----------------
Subconfig: index_redirect
Value:     "login"
----------------
Subconfig: manual
Value:     false
----------------
Subconfig: localhost_manual
Value:     false
----------------
################################
Config: colors
----------------
Subconfig: countdown
Value:     "#1b3faa"
----------------
Subconfig: background_countdown
Value:     "#8d9fd4"
----------------
Subconfig: cheese
Value:     "#aa1b3f"
----------------
Subconfig: primary
Value:     "#1b3faa"
----------------
Subconfig: primary_light
Value:     "#e8ebf6"
----------------
Subconfig: secondary
Value:     "#5f78c3"
----------------
Subconfig: highlight
Value:     "#8d9fd4"
----------------
Subconfig: font
Value:     "#c9c9c9"
----------------
Subconfig: font_secondary
Value:     "#333333"
----------------
Subconfig: button_font
Value:     "#ffffff"
----------------
Subconfig: start_font
Value:     "#333333"
----------------
Subconfig: panel
Value:     "#000000"
----------------
Subconfig: border
Value:     "#eeeeee"
----------------
Subconfig: box
Value:     "#e8ebf6"
----------------
Subconfig: gallery_button
Value:     "#ffffff"
----------------
################################
Config: background
----------------
Subconfig: defaults
Value:     "url(\/resources\/img\/background.png)"
----------------
Subconfig: chroma
Value:     "url(\/resources\/img\/background.png)"
----------------
Subconfig: admin
Value:     "url(\/resources\/img\/background.png)"
----------------
################################
Config: jpeg_quality
----------------
Subconfig: image
Value:     100
----------------
Subconfig: chroma
Value:     100
----------------
Subconfig: thumb
Value:     60
----------------
################################
Config: take_picture
----------------
Subconfig: cmd
Value:     "python3 cameracontrol.py --capture-image-and-download %s"
----------------
################################
Config: exiftool
----------------
Subconfig: cmd
Value:     "exiftool -overwrite_original -TagsFromFile %s %s"
----------------
################################
Config: nodebin
----------------
Subconfig: cmd
Value:     "\/usr\/bin\/node"
----------------
################################
Config: pre_photo
----------------
Subconfig: cmd
Value:     ""
----------------
################################
Config: post_photo
----------------
Subconfig: cmd
Value:     ""
----------------
################################
Config: reboot
----------------
Subconfig: cmd
Value:     "\/sbin\/shutdown -r now"
----------------
################################
Config: shutdown
----------------
Subconfig: cmd
Value:     "\/sbin\/shutdown -h now"
----------------
################################
Config: folders
----------------
Subconfig: config
Value:     "config"
----------------
Subconfig: data
Value:     "data"
----------------
Subconfig: images
Value:     "images"
----------------
Subconfig: keying
Value:     "keying"
----------------
Subconfig: print
Value:     "print"
----------------
Subconfig: qrcodes
Value:     "qrcodes"
----------------
Subconfig: thumbs
Value:     "thumbs"
----------------
Subconfig: tmp
Value:     "tmp"
----------------
Subconfig: archives
Value:     "archives"
----------------
Subconfig: private
Value:     "private"
----------------
################################
Config: reset
----------------
Subconfig: remove_images
Value:     true
----------------
Subconfig: remove_mailtxt
Value:     false
----------------
Subconfig: remove_config
Value:     false
----------------
Subconfig: remove_print_db
Value:     false
----------------
################################
Config: take_video
----------------
Subconfig: cmd
Value:     "python3 cameracontrol.py -v %s --vlen 3 --vframes 4"
----------------
################################
Config: foldersAbs
----------------
Subconfig: config
Value:     "\/var\/www\/html\/config"
----------------
Subconfig: data
Value:     "\/var\/www\/html\/data"
----------------
Subconfig: images
Value:     "\/var\/www\/html\/data\/images"
----------------
Subconfig: keying
Value:     "\/var\/www\/html\/data\/keying"
----------------
Subconfig: print
Value:     "\/var\/www\/html\/data\/print"
----------------
Subconfig: qrcodes
Value:     "\/var\/www\/html\/data\/qrcodes"
----------------
Subconfig: thumbs
Value:     "\/var\/www\/html\/data\/thumbs"
----------------
Subconfig: tmp
Value:     "\/var\/www\/html\/data\/tmp"
----------------
Subconfig: archives
Value:     "\/var\/www\/html\/archives"
----------------
Subconfig: private
Value:     "\/var\/www\/html\/private"
----------------
Subconfig: var
Value:     "\/var\/www\/html\/var"
----------------
################################
Config: foldersPublic
----------------
Subconfig: images
Value:     "\/data\/images"
----------------
Subconfig: keying
Value:     "\/data\/keying"
----------------
Subconfig: print
Value:     "\/data\/print"
----------------
Subconfig: qrcodes
Value:     "\/data\/qrcodes"
----------------
Subconfig: thumbs
Value:     "\/data\/thumbs"
----------------
Subconfig: tmp
Value:     "\/data\/tmp"
----------------
Subconfig: api
Value:     "\/api"
----------------
Subconfig: chroma
Value:     "\/chroma"
----------------
################################
Config: photobooth
----------------
Subconfig: version
Value:     "4.3.1"
----------------
Subconfig: basePath
Value:     "\/"
----------------""

### Expected behavior

Live view from the camera

### Photobooth Version

Actual Version

### Operating System

Raspberry Pi4

### Did it work before?

No

**Comment by Styne13** [comment] 2024-01-26 21:37
Seems to be similar to #527 

Tried out the steps mentioned there, but also can not get a live view with my Nikon D3100. If I run the command for live preview as www-data in a separat terminal, I am able to get a preview on the home screen, but only with chromium.

For me it looks like it has something to do with the way photobooth starts the script, but had no time yet to investigate further.

**Comment by andi34** [comment] 2024-01-27 07:21
Duplicate of https://github.com/PhotoboothProject/photobooth/issues/527

**Closed by andi34** 2024-01-27 07:21 UTC
Labels: bug

**Comment by andi34** [comment] 2024-01-27 07:39
There currently seems to be an issue while using the cameracontrol.py we're looking at already.

For now you could setup again by scratch and run the installer via:
```
sudo bash install-photobooth.sh -username='YourUsername' --mjpeg
```
This will install go2rtc and also allows a remote preview. 
Adjust the Capture command:
`capture %`

And Set preview `from URL` as preview and define the URL: `url("http://localhost:1984/api/stream.mjpeg?src=dslr")`


Another problem might be Firefox which isn't related to Photobooth and can't be fixed by us. Firefox-ESR was told to work.

**Comment by Tobi392** [comment] 2024-01-27 13:52
Hi, thanks for your response.
Live view works now fine.
But with only the command "capture %" i'm running into an error, last log is:
[2024-01-27 13:51:05][main][DEBUG] Capture with CMD {"cmd":"capture %","tmpFile":"/var/www/html/data/tmp/20240127_135105.jpg"}
Do i need to add any download command or something else?

**Comment by andi34** [comment] 2024-01-27 14:03
Sorry, Typo

```
capture %s
```
